core/urls.py
from django.urls import path

from core.views.view import *
from core.views.create import *
from core.views.edit import *
from core.views.list import *
from core.views.delete import *
from core.views.home import *

from core.views.document import *
from core.views.export import *
from core.views.action import *

from core.views.api.list import *
from core.views.api.operation import *
from core.views.api.checkpoint import *
from core.views.create_company import *

app_name = "core"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("list/<str:app>/<str:model>", List.as_view(), name="list"),
    path("create/<str:app>/<str:model>", Create.as_view(), name="create"),
    path("edit/<str:app>/<str:model>/<int:pk>", Edit.as_view(), name="edit"),
    path("view/<str:app>/<str:model>/<int:pk>", Overview.as_view(), name="view"),
    path("delete/<str:app>/<str:model>/<int:pk>", Delete.as_view(), name="delete"),

    path("document/<str:app>/<str:model>/<str:template>", Document.as_view(), name="document"),
    path("action/<str:app>/<str:model>/<str:verbose>", Action.as_view(), name="action"),
    path("export/<str:app>/<str:model>", Export.as_view(), name="export"),

    path("check-point-operation/<int:checkpoint>", CheckPointATM.as_view(), name="check-point-operation"),
    path("api-check-point-operation", OperationAPIView.as_view(), name="api-check-point-operation"),
    path("api-list/<str:app>/<str:model>", ListAPI.as_view(), name="api-list"),

    path("create-company", CreateCompany.as_view(), name="create-company")
]

lmcservice/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),

    path('', include('django.contrib.auth.urls')),

    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),

    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('core.urls'))
]

core/views/action.py
from django.shortcuts import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.apps import apps

from django.db.models.signals import post_save
from django.contrib.admin.models import LogEntry, CHANGE
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.mixins import PermissionRequiredMixin


class Action(LoginRequiredMixin, PermissionRequiredMixin, View):
    def get_permission_required(self):
        data = self.kwargs
        return f"{data.get('app')}.change_{data.get('model')}",

    def post(self, request, app, model, verbose):
        model = apps.get_model(app, model)
        data = request.POST.dict()
        del data["csrfmiddlewaretoken"]

        qs = model.objects.filter(**request.GET.dict())
        if not qs.exists():
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

        actions = [action for action in model.change_actions
                   if action.get("prerequisite") and action.get("verbose_name") == verbose]
        actions = actions[0] if len(actions) == 1 else {}

        if actions.get("prerequisite", False):
            prerequisite = actions.get("prerequisite")
            obj = qs.last()
            if not eval(prerequisite.get("condition")):
                messages.error(request, prerequisite.get("message", {}).get("error", "We fail this action"))
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            action = eval(prerequisite.get("action", "False"))
            if action: messages.success(request, prerequisite.get("message", {}).get("success", "Action success"))

        qs.update(**data)
        post_save.send(model, instance=qs.last(), created=False)
        messages.success(request, "Action updated successfully")

        obj = qs.last()
        LogEntry.objects.log_action(user_id=request.user.id, content_type_id=ContentType.objects.get_for_model(obj).pk,
                                    object_id=obj.id, object_repr=f"Modification de {obj}",
                                    action_flag=CHANGE, change_message=str(data))

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

core/views/create.py
from django.contrib import messages
from django.apps import apps

from django.forms import modelform_factory, inlineformset_factory
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, reverse, redirect
from django.views import View

from core.utils import modelform_factory_data

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.models import LogEntry, ADDITION
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.admin.utils import construct_change_message

from django.db import transaction


class Create(LoginRequiredMixin, PermissionRequiredMixin, View):

    def get_permission_required(self):
        data = self.kwargs
        return f"{data.get('app')}.add_{data.get('model')}",

    def get(self, request, app, model):
        model = apps.get_model(app, model)

        data = modelform_factory_data(model)
        form = modelform_factory(model, **data)

        if hasattr(model, "inline_model_form"):
            inline = getattr(model, "inline_model_form")
            _model = apps.get_model(app_label=inline.get("app_label"), model_name=inline.get("model_name"))
            _fields = _model.form_fields if hasattr(_model, "form_fields") else "__all__"
            inlineformset = inlineformset_factory(model, _model, form=modelform_factory(_model, fields=_fields),
                                                  extra=1, can_delete=False)
        return render(request, f"core/create.html", locals())

    def post(self, request, app, model):
        model = apps.get_model(app, model)

        data = modelform_factory_data(model)
        form = modelform_factory(model, **data)(request.POST, request.FILES)

        inlineformset = None
        if hasattr(model, "inline_model_form"):
            inline = getattr(model, "inline_model_form")
            _model = apps.get_model(app_label=inline.get("app_label"), model_name=inline.get("model_name"))
            _fields = _model.form_fields if hasattr(_model, "form_fields") else "__all__"
            inlineformset = inlineformset_factory(model, _model, form=modelform_factory(_model, fields=_fields))
            inlineformset = inlineformset(request.POST, request.FILES)

        if not form.is_valid() or (inlineformset and not inlineformset.is_valid()):
            return render(request, f"core/create.html", locals())

        obj = form.save(commit=False)
        if isinstance(obj, apps.get_model("service", "operation")):
            obj.created_by = request.user
            obj.company = request.user.company
        if isinstance(obj, apps.get_model("core", "user")): obj.company = request.user.company
        obj.save()

        # Inherent permission
        if isinstance(obj, apps.get_model("core", "user")): obj.groups.add(*list(request.user.groups.all()))

        if hasattr(model, "inline_model_form"):
            with transaction.atomic():
                inlines = inlineformset.save(commit=False)
                for inline in inlines:
                    if not hasattr(inline, inlineformset.fk.name): continue
                    setattr(inline, inlineformset.fk.name, obj)
                    inline.save()

        messages.success(request, f"{model._meta.verbose_name} created successfully")
        message = construct_change_message(form, None, True)
        LogEntry.objects.log_action(user_id=request.user.id, content_type_id=ContentType.objects.get_for_model(obj).pk,
                                    object_id=obj.id, object_repr=f"Creation de {obj}",
                                    action_flag=ADDITION, change_message=str(message))
        return redirect(reverse('core:edit', kwargs={"app": app, "model": model._meta.model_name, "pk": form.instance.id}))

core/views/create_company.py
from django.contrib import messages
from django.apps import apps

from django.forms import modelform_factory, inlineformset_factory
from django.shortcuts import render, reverse, redirect
from django.views import View

from core.utils import modelform_factory_data


class CreateCompany(View):
    def get(self, request):
        model = apps.get_model("service", "company")
        data = modelform_factory_data(model)
        form = modelform_factory(model, **data)
        return render(request, f"registration/create_company.html", locals())

    def post(self, request):
        model = apps.get_model("service", "company")
        data = modelform_factory_data(model)
        form = modelform_factory(model, **data)(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, f"registration/create_company.html", locals())
        form.save()

        messages.success(request, f"{model._meta.verbose_name} created successfully")
        messages.success(request, "We are reviewing your registration, and will mail your with a confirmation")
        return redirect(reverse('login'))

core/views/delete.py
from django.apps import apps

from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.models import LogEntry, DELETION


class Delete(LoginRequiredMixin, PermissionRequiredMixin, View):

    def get_permission_required(self):
        data = self.kwargs
        return f"{data.get('app')}.delete_{data.get('model')}",

    def get(self, request, app, model, pk):
        model = apps.get_model(app, model)

        obj = get_object_or_404(model, pk=pk)
        return render(request, f"core/delete.html", locals())

    def post(self, request, app, model, pk):
        model = apps.get_model(app, model)

        obj = get_object_or_404(model, pk=pk)
        LogEntry.objects.log_action(user_id=request.user.id, content_type_id=ContentType.objects.get_for_model(obj).pk,
                                    object_id=obj.id, object_repr=f"Suppression de {obj}",
                                    action_flag=DELETION, change_message="{}")
        obj.delete()
        return redirect(reverse('core:list', kwargs={"app": app, "model": model._meta.model_name}))

core/views/document.py
from django.apps import apps
from django.views import View
from django.db.models import Count, Sum
from django.shortcuts import render, get_object_or_404


# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.mixins import PermissionRequiredMixin


class Document(View):
    def get_permission_required(self):
        data = self.kwargs
        return f"{data.get('app')}.view_{data.get('model')}",

    def get(self, request, app, model, template, output="pdf"):
        model = apps.get_model(app, model)
        obj = get_object_or_404(model, **request.GET.dict())
        if hasattr(model, "inline_model_form"):
            data = getattr(model, "inline_model_form", {})
            _model = apps.get_model(app_label=data.get("app_label"), model_name=data.get("model_name"))
            qs = _model.objects.filter(**{model._meta.model_name: obj.id})
            if template == "invoice":
                qs = qs.values('product_type__name', 'product_type__fees', 'penalty').annotate(count=Sum('quantity'))
        return render(request, f"document/{template}.html", locals())

core/views/edit.py
from django.contrib import messages
from django.apps import apps

from django.contrib.contenttypes.models import ContentType
from django.forms import modelform_factory, inlineformset_factory
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views import View

from core.utils import modelform_factory_data
from django.forms.fields import TypedChoiceField

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.models import LogEntry, CHANGE
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.admin.utils import construct_change_message


def modelAndFields(request, model):
    inline = getattr(model, "inline_model_form")
    _model = apps.get_model(app_label=inline.get("app_label"), model_name=inline.get("model_name"))
    _fields = [field for field in _model.form_fields] if hasattr(model, "form_fields") else "__all__"

    if hasattr(_model, "extra") and "fields" in _model.extra:
        for field in _model.extra.get("fields"):
            if eval(field.get("condition")):
                _fields.append(field.get("name"))
    return _model, _fields


class Edit(LoginRequiredMixin, PermissionRequiredMixin, View):

    def get_permission_required(self):
        data = self.kwargs
        return f"{data.get('app')}.change_{data.get('model')}",

    def get(self, request, app, model, pk):
        model = apps.get_model(app, model)

        obj = get_object_or_404(model, pk=pk)
        data = modelform_factory_data(model)

        # check if the model can manage edit requirement
        if hasattr(model, "editable_if"):
            if not eval(model.editable_if):
                return redirect(reverse("core:view", kwargs={"app": app, "model": model._meta.model_name, "pk": pk}))

        if hasattr(model, "extra") and "fields" in model.extra:
            for field in model.extra.get("fields"):
                if eval(field.get("condition")):
                    data["fields"].append(field.get("name"))

        form = modelform_factory(model, **data)(instance=obj)

        if request.user.is_staff and request.user.office \
                and request.user.office.limitation.get("value", {}).get(model._meta.model_name, False):
            for key, value in request.user.office.limitation.get("value", {}).get(model._meta.model_name, {}).items():
                if key not in form.fields or value is None: continue
                if not isinstance(form.fields[key], TypedChoiceField): continue
                form.fields[key].choices = [choice for choice in form.fields[key].choices if choice[0] in value]

        if hasattr(model, "inline_model_form"):
            inline = modelAndFields(request, model)
            inlineformset = inlineformset_factory(model, inline[0], form=modelform_factory(inline[0], fields=inline[1]),
                                                  extra=1, can_delete=True)(instance=obj)

        return render(request, f"core/update.html", locals())

    def post(self, request, app, model, pk):
        model = apps.get_model(app, model)
        obj = get_object_or_404(model, pk=pk)

        data = modelform_factory_data(model)

        if hasattr(model, "extra") and "fields" in model.extra:
            for field in model.extra.get("fields"):
                if eval(field.get("condition", "False")):
                    data["fields"].append(field.get("name"))

        form = modelform_factory(model, **data)(request.POST, request.FILES, instance=obj)

        if request.user.is_staff and request.user.office \
                and request.user.office.limitation.get("value", {}).get(model._meta.model_name, False):
            for key, value in request.user.office.limitation.get("value", {}).get(model._meta.model_name, {}).items():
                if key not in form.fields or value is None: continue
                if not isinstance(form.fields[key], TypedChoiceField): continue
                form.fields[key].choices = [choice for choice in form.fields[key].choices if choice[0] in value]

        inlineformset = None
        if hasattr(model, "inline_model_form"):
            inline = modelAndFields(request, model)
            inlineformset = inlineformset_factory(model, inline[0], form=modelform_factory(inline[0], fields=inline[1])
                                                  , extra=1, can_delete=True)(request.POST, request.FILES, instance=obj)

        if not form.is_valid() or (inlineformset and not inlineformset.is_valid()):
            return render(request, f"core/update.html", locals())

        obj = form.save(commit=True)
        if isinstance(obj, apps.get_model("service", "operation")): obj.updated_by = request.user

        obj.save()
        if hasattr(model, "inline_model_form"): inlineformset.save()
        messages.success(request, f"{model._meta.verbose_name} {getattr(obj, 'status', '')} updated successfully")

        message = construct_change_message(form, None, False)
        LogEntry.objects.log_action(user_id=request.user.id, content_type_id=ContentType.objects.get_for_model(obj).pk,
                                    object_id=obj.id, object_repr=f"Modification de {obj}",
                                    action_flag=CHANGE, change_message=str(message))
        return redirect(reverse('core:edit', kwargs={"app": app, "model": model._meta.model_name, "pk": pk}))

templates/core/list.html
{% extends 'base.html' %}

{% load i18n %}
{% load core %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.0/jsoneditor.js" integrity="sha512-6IR2k2uL9AnAl2jxtTjGVDbqJ231btVidKH2ZOwU3L6lLPAlm88Zcm5/8unssV6nQwB25RcvA3k3JWYdwMumkQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock head %}

{% block content %}
    <div>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2 text-capitalize">{{ model|getattr:'_meta'|getattr:'verbose_name' }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                    {% with model|getattr:'_meta'|getattr:'model_name' as model_name %}
                        {% with app|stringbuilder:".add_"|stringbuilder:model_name as perm %}
                            {% if perm in perms %}
                                <a href="{% url 'core:create' app model|getattr:'_meta'|getattr:'model_name' %}" class="btn btn-sm btn-outline-secondary">
                                    {% trans 'Add' %}
                                </a>
                            {% endif %}
                        {% endwith %}
                    {% endwith %}

                  {% for action in model.list_actions %}
                      {% if action.permission in perms %}
                          <a href="{{ action.url }}?{{ request.GET.urlencode }}" class="btn btn-sm btn-outline-primary">{% trans action.verbose_name %}</a>
                      {% endif %}
                  {% endfor %}
              </div>
            </div>
        </div>

        <div class="row">
            <div class="col{% if filter %}-md-10{% endif %}">
                <div class="row">
                    {% if total_cost %}
                        <div class="col-2">Total Cost : <h4>{{ total_cost|intcomma }}</h4></div>
                    {% endif %}
                    <div class="col">
                        <form method="get">
                            <div class="input-group mb-3">
                              <input type="search" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="{% trans 'Search' %}" aria-label="Search" aria-describedby="basic-addon2">
                              <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-sm" type="submit">{% trans 'Search' %}</button>
                              </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                      <thead>
                        <tr>
                            {% for field in fields %}
                                <th class="text-capitalize">{{ field }}</th>
                            {% endfor %}
                            <th>{% trans 'Actions' %}</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for obj in qs %}
                            <tr>
                                {% for field in fields %}
                                <td>
                                    {% if field == "status" %}
                                        <span class="badge badge-{{ obj|getdict:field|displaystatus }}">{{ obj|getdict:field|default:"-" }}</span>
                                    {% elif field == "cost" or field == "total" %}
                                        {{ obj|getdict:field|default:0.0|intcomma }}
                                    {% else %}
                                        {{ obj|getdict:field|default:"-" }}
                                    {% endif %}
                                </td>
                                {% endfor %}
                                <td>
                                    {% with model|getattr:'_meta'|getattr:'model_name' as model_name %}
                                        {% with app|stringbuilder:".change_"|stringbuilder:model_name as perm %}
                                            {% if perm in perms %}
                                                <a href="{% url 'core:edit' model|getattr:'_meta'|getattr:'app_label' model|getattr:'_meta'|getattr:'model_name' obj|getdict:'id' %}">
                                                    {% trans 'Change' %}
                                                </a>
                                            {% endif %}
                                        {% endwith %}|
                                        {% with app|stringbuilder:".view_"|stringbuilder:model_name as perm %}
                                            {% if perm in perms %}
                                                <a href="{% url 'core:view' model|getattr:'_meta'|getattr:'app_label' model|getattr:'_meta'|getattr:'model_name' obj|getdict:'id' %}">
                                                    {% trans 'View' %}
                                                </a>
                                            {% endif %}
                                        {% endwith %}
                                    {% endwith %}

                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td class="text-center text-uppercase" colspan="10">
                                    <h5>No {{ model|getattr:'_meta'|getattr:'verbose_name' }} found</h5>
                                </td>
                            </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
            {% if filter %}
                <div class="col-md-2">
                    <form method="get">
                        {{ filter.form|crispy }}
                        <button type="submit" class="btn btn-secondary btn-sm col">{% trans "Submit" %}</button>
                    </form>
                </div>
            {% endif %}
        </div>

        {% if qs.has_other_pages %}
            <div class="col text-center mb-5">
                <div class="btn-group" role="group" aria-label="Basic example">
                    {% if qs.has_previous %}
                    <a href="?{% for key,value in query.items %}{{ key }}={{ value }}{% endfor %}&page={{ qs.previous_page_number }}" class="btn btn-secondary">{% trans "Previous" %}</a>
                    {% endif %}
                    <a href="#" class="btn btn-secondary">{{ request.GET.page|default:1 }}</a>
                    <a href="?{% for key,value in query.items %}{{ key }}={{ value }}{% endfor %}&page={{ qs.next_page_number }}" class="btn btn-secondary">{% trans "Next" %}</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/core/update.html
{% extends 'base.html' %}

{% load i18n %}
{% load core %}
{% load crispy_forms_tags %}


{% block content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js" integrity="sha512-Tsdobfrx6IMRPi8d5z3AtjWNSbZxGm58IZFnblaRaepw562ZITlRhUM2Zu87vbvZjQxGmmto+31zEBLZ4wjs+w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <div style="z-index: -1; position: fixed; color: grey;opacity: 0.1;">
        <h1 style="font-size: 10rem;">{{ model|getattr:'_meta'|getattr:'verbose_name' }}</h1>
    </div>

    <div>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <div>
                <h1 class="h2 text-capitalize mb-0">
                    {{ model|getattr:'_meta'|getattr:'verbose_name' }} #{{ obj.id }}
                    {% if obj.status %}
                        <span class="badge badge-{{ obj.status|displaystatus }}">{{ obj.status }}</span>
                    {% endif %}
                </h1>
                <small>
                    {% with model|getattr:'_meta'|getattr:'model_name' as model_name %}
                        {% with app|stringbuilder:".delete_"|stringbuilder:model_name as perm %}
                            {% if perm in perms %}
                                <a href="{% url 'core:list' app model|getattr:'_meta'|getattr:'model_name' %}" class="text-capitalize">{{ model|getattr:'_meta'|getattr:'verbose_name_plural' }}</a> /
                            {% endif %}
                        {% endwith %}
                    {% endwith %}
                    {{ obj.id }}
                </small>
            </div>

        <form id="submit-form" method="post">
            {% csrf_token %}
            <input type="hidden" name="status" value="SUBMITTED">
        </form>

            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">

                    {% with model|getattr:'_meta'|getattr:'model_name' as model_name %}
                        {% with app|stringbuilder:".delete_"|stringbuilder:model_name as perm %}
                            {% if perm in perms %}
                                <a href="{% url 'core:delete' app model_name obj.id %}" class="btn btn-sm btn-outline-danger">{% trans 'Delete' %}</a>
                            {% endif %}
                        {% endwith %}
                    {% endwith %}

                    {% for action in model.change_actions %}
                      {% if action.permission in perms and obj|attrmatch:action.limitation and action.method == "GET" and action.condition|eval:request %}
                          <a target="_blank" href="{{ action.url }}?id={{ obj.id }}" class="btn btn-sm btn-outline-primary">{{ action.verbose_name }}</a>
                      {% endif %}
                    {% endfor %}

                <button class="btn btn-sm btn-outline-success" type="submit" form="form-container">{% trans 'Save' %}</button>
              </div>

                {% for action in model.change_actions %}
                  {% if action.permission in perms and obj|attrmatch:action.limitation and action.method == "POST" and action.condition|eval:request %}
                      <form action="{{ action.url }}?id={{ pk }}" id="form-{{ action.verbose_name }}" method="{{ action.method }}">
                        {% csrf_token %}
                        {% for key, value in action.values.items %}
                            <input type="hidden" name="{{ key }}" value="{{ value }}">
                        {% endfor %}
                        <button type="submit" class="btn btn-sm btn-outline-primary">{{ action.verbose_name }}</button>
                      </form>
                  {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="mb-5">

        {%  if form.errors  %}
            {% for error in form.errors.as_data.values %}
                {% for data in error.0 %}
                    <div class="alert alert-danger">
                        <ul class="messages mb-0 text-uppercase">
                            <li>{{ data }}</li>
                        </ul>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <form method="post" id="form-container" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.non_form_errors }}

            {% if form.fields|length > 4 %}
             <div class="form-row">
                {% for field in form %}
                    <div {% if field.field.widget.input_type != 'hidden' %}class="col-md-4"{% endif %}>
                        {{ field|as_crispy_field }}
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <div>
                    {{ form|crispy }}
                </div>
            {% endif %}

            {% if inline %}
                <hr class="mt-3 mb-5">
                <h5 class="text-info">{{ inline.0|getattr:'_meta'|getattr:'verbose_name' }}(s)</h5>
                {{ inlineformset.non_form_errors }}
                {{ inlineformset.management_form }}

                {% for form in inlineformset %}
                    <div class="formset_row">
                        {% if form.instance %}
                            <h2>#{{ form.instance.id }}</h2>
                        {% endif %}
                        <div class="d-flex py-1 inline {{ inlineformset.prefix }}">
                            <div class="form-row">
                                {% for field in form %}
                                    <div {% if field.field.widget.input_type != 'hidden' %}class="col-md-3"{% endif %}>
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <hr/>
                {% endfor %}
            {% endif %}
        </form>
    </div>

    <script type="text/javascript">
        $('.formset_row').formset({addText: "Add", deleteText: 'remove', prefix: '{{ inlineformset.prefix }}'});
    </script>

{% endblock content %}