core/urls.py
from django.urls import path

from core.views.view import *
from core.views.create import *
from core.views.edit import *
from core.views.list import *
from core.views.delete import *
from core.views.home import *

from core.views.document import *
from core.views.export import *
from core.views.action import *

from core.views.api.list import *
from core.views.api.operation import *
from core.views.api.checkpoint import *
from core.views.create_company import *

app_name = "core"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("list/<str:app>/<str:model>", List.as_view(), name="list"),
    path("create/<str:app>/<str:model>", Create.as_view(), name="create"),
    path("edit/<str:app>/<str:model>/<int:pk>", Edit.as_view(), name="edit"),
    path("view/<str:app>/<str:model>/<int:pk>", Overview.as_view(), name="view"),
    path("delete/<str:app>/<str:model>/<int:pk>", Delete.as_view(), name="delete"),

    path("document/<str:app>/<str:model>/<str:template>", Document.as_view(), name="document"),
    path("action/<str:app>/<str:model>/<str:verbose>", Action.as_view(), name="action"),
    path("export/<str:app>/<str:model>", Export.as_view(), name="export"),

    path("check-point-operation/<int:checkpoint>", CheckPointATM.as_view(), name="check-point-operation"),
    path("api-check-point-operation", OperationAPIView.as_view(), name="api-check-point-operation"),
    path("api-list/<str:app>/<str:model>", ListAPI.as_view(), name="api-list"),

    path("create-company", CreateCompany.as_view(), name="create-company")
]

lmcservice/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),

    path('', include('django.contrib.auth.urls')),

    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),

    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('core.urls'))
]

core/views/home.py
from django.shortcuts import render
from django.db.models import Count
from django.views import View
from service import models
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin


class Home(LoginRequiredMixin, View):
    def get(self, request):
        # filter last 3 months
        last_3_months = datetime.today() - timedelta(days=90)
        qs = models.Operation.objects.filter(created__gte=last_3_months)

        # case of staff
        if request.user.is_staff and request.user.office is not None:
            _data = request.user.office.limitation.get("field", {}).get("operation", {})
            _data = {key: value for key, value in _data.items() if value}
            qs = qs.filter(**request.user.office.limitation.get("field", {}).get("operation", {}))

        # Case of forwarder user
        if request.user.company is not None: qs = qs.filter(company=request.user.company)

        data = {"pie": {"labels": [], "data": []}, "bar": {"labels": [], "data": {}}}

        status = qs.values("status").annotate(Count("status"))

        for pie in status:
            data["pie"]["labels"].append(pie.get("status"))
            data["pie"]["data"].append(pie.get("status__count"))

        bars = qs.values("status", "created__month").annotate(Count("status"))

        for bar in bars:
            data["bar"]["labels"].append(bar.get("created__month"))
            if bar.get("status") not in data["bar"]["data"]:
                data["bar"]["data"][bar.get("status")] = []
            data["bar"]["data"][bar.get("status")].append(bar.get("status__count"))

        data["bar"]["labels"] = [datetime.strptime(str(label), "%m").strftime("%B") for label in data["bar"]["labels"]]
        data["bar"]["labels"] = list(set(data["bar"]["labels"]))
        return render(request, "home.html", locals())

templates/base.html
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% get_current_language as LANGUAGE_CODE %}

{% load core %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon"href="{% static 'favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Lignes Martimes Congolaises{% endblock title %}</title>

    <meta name="description" content="{% block description %}LMC Services{% endblock description %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% comment %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% endcomment %}

    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.0/jsoneditor.css" integrity="sha512-/JghmMAi5bleEgj1BT7h7Jm2+o4I4AbJYRVaY3eGGfdyTzV+yW3n0IedWH4ysbws5zpNK1beCqVJh0MSZxvNaA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.0/jsoneditor.js" integrity="sha512-6IR2k2uL9AnAl2jxtTjGVDbqJ231btVidKH2ZOwU3L6lLPAlm88Zcm5/8unssV6nQwB25RcvA3k3JWYdwMumkQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <style>
        body {
          font-size: .775rem;
        }

        input, select, textarea{
            font-size: .775rem !important;
        }

        .form-text{
            margin-top: 0px !important;
        }

        .feather {
          width: 16px;
          height: 16px;
          vertical-align: text-bottom;
        }

        /*
         * Sidebar
         */

        .sidebar {
          position: fixed;
          top: 0;
          bottom: 0;
          left: 0;
          z-index: 100; /* Behind the navbar */
          padding: 0;
          box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        .sidebar-sticky {
          position: -webkit-sticky;
          position: sticky;
          height: calc(100vh - 48px);
          padding-top: .5rem;
          overflow-x: hidden;
          overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        .sidebar .nav-link {
          font-weight: 500;
          color: #333;
        }

        .sidebar .nav-link .feather {
          margin-right: 4px;
          color: #999;
        }

        .sidebar .nav-link.active {
          color: #007bff;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
          color: inherit;
        }

        .sidebar-heading {
          font-size: .75rem;
          text-transform: uppercase;
        }

        /*
         * Navbar
         */

        .navbar-brand {
          padding-top: .75rem;
          padding-bottom: .75rem;
          font-size: 1rem;
          background-color: rgba(0, 0, 0, .25);
          box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
        }

        .navbar .form-control {
          padding: .75rem 1rem;
          border-width: 0;
          border-radius: 0;
        }

        .form-control-dark {
          color: #fff;
          background-color: rgba(255, 255, 255, .1);
          border-color: rgba(255, 255, 255, .1);
        }

        .form-control-dark:focus {
          border-color: transparent;
          box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
        }

        /*
         * Utilities
         */

        .border-top { border-top: 1px solid #e5e5e5; }
        .border-bottom { border-bottom: 1px solid #e5e5e5; }
    </style>
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'core:home' %}">
        {{ request.user.company|default:request.user.office|default:request.user.get_full_name|default:"-" }}
      </a>

      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% if request.user.company %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item text-nowrap font-weight-bold h5">
              <span class="badge badge-primary">[{{ request.user.company.balance }}]</span>
            </li>
          </ul>
      {% endif %}

        <ul class="navbar-nav px-2">
        <li class="nav-item text-nowrap">
          <a class="nav-link text-light" href="{% url 'core:edit' 'core' 'user' request.user.id %}">
              {{ request.user.get_full_name|default:request.user.email }}
          </a>
        </li>
      </ul>

      <ul class="navbar-nav px-2">
        <li class="nav-item text-nowrap">
          <a class="nav-link text-danger" href="{% url "logout" %}">{% trans "Logout" %}</a>
        </li>
      </ul>
    </header>


    <div class="container-fluid">
      <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-dark text-light sidebar">
      <div class="sidebar-sticky">

        {% comment %}
        <div class="col text-center mt-1 mb-1">
            <img width="64" src="{% static 'image/logo.png' %}" class="img-fluid" />
        </div>

        {% if request.user.company %}
            <h4 class="text-center">{{ request.user.company.name }}</h4>
            <h6 class="text-center">
                <small>{% trans "Hey!" %} <br /> {{ request.user.get_full_name|default:request.user.email }}</small>
            </h6>
            {% else %}
            <h4 class="text-center">
                Lignes Maritimes Congolaises
                {% if requser.user.office %}
                    {{ request.user.office.name }}
                {% endif %}
            </h4>
            <h6 class="text-center">
                <small>{% trans "Hey!" %} {{ request.user.get_full_name|default:request.user.email }}</small>
            </h6>
        {% endif %}

        {% endcomment %}

        <ul class="nav flex-column mt-5 mb-1">
          <li class="nav-item">
            <a class="nav-link text-light {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'core:home' %}">
              {% trans 'Home' %} <span class="sr-only">(current)</span>
            </a>
            <a class="nav-link text-capitalize text-warning" href="{% url 'password_reset' %}">
                {% trans 'Reset password' %}<span class="sr-only">(current)</span>
            </a>
          </li>

          {% with request.user|models as apps %}
              {% for key, models in apps.items %}
                  <li class="nav-item">
                    <a class="nav-link text-capitalize text-muted" href="#">
                      {{ key }} <span class="sr-only">(current)</span>
                    </a>
                    <ul>
                        {% for model in models %}
                            <li class="text-capitalize">
                                <a class="nav-link text-capitalize {% if request.resolver_match.kwargs.model == model.name %}active{% else %}text-light{% endif %}" href="{% url 'core:list' key model.name %}">
                                  {{ model.verbose }} <span class="sr-only">(current)</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                  </li>
              {% endfor %}
          {% endwith %}
        </ul>
      </div>
    </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        <ul class="messages mb-0 text-uppercase">
                            <li>{{ message|safe }}</li>
                        </ul>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock content %}
        </main>

      </div>
    </div>

    <script>
        $(document).ready(function() {
            $("input, select").addClass("form-control-sm");
            $(".add-row").addClass("col btn btn-primary mt-3");
            $(".selectmultiple").select2();

            $("select").each(function(){
                const len = $(this).find("option").length;
                if(len > 20) $(this).select2();
            });
        });
    </script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load core %}
{% load i18n %}

{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <div>
        <h3 class="mb-0">{% trans 'Home' %}</h3>
        <small>Lignes Maritimes Congolaises</small>
    </div>

    <div class="row mt-3">
        {% for state in status %}
            <div class="card col bg-{{ state.status|displaystatus }} text-white m-1">
                <div class="card-body">
                    <h5>{{ state.status }}</h5>
                    <h6>{{ state.status__count }}</h6>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row mt-5">
        <div class="col-md-7">
            <h4>Period performance by operation</h4>
            <canvas id="line-chart"></canvas>
        </div>
        <div class="col-md-5">
            <canvas id="pie-chart"></canvas>
            <small class="text-center text-muted mt-2">Global operation overview</small>
        </div>
    </div>



    <script>
    const charts = {
        pie: {
          type: 'pie',
          data: {
            datasets: [{
              label: "Population",
              data: {{ data.pie.data|safe }},
              backgroundColor: ["#6c757d", "#28a745", "#A9A9A9", "#C0C0C0", "#D3D3D3"]
            }],
            labels: {{ data.pie.labels|safe }}
          },
          options: {
            responsive: true
          }
        },
        line: {
          type: 'bar',
          data: {
            labels: {{ data.bar.labels|safe }},
            datasets: [{% for key, value in data.bar.data.items %}
                {
                    data: {{ value|safe }},
                    label: "{{ key }}",
                    backgroundColor: ["#6c757d", "#28a745", "#A9A9A9", "#C0C0C0", "#D3D3D3"]
                },
            {% endfor %}]
          },
        }
    };

    window.onload = function() {
      window.myPie = new Chart(document.getElementById('pie-chart').getContext('2d'), charts.pie);
      window.myLine = new Chart(document.getElementById('line-chart').getContext('2d'), charts.line);
    };
    </script>

{% endblock %}